### ISSUE TITLE
ADS integration Exec format error

### ISSUE THREAD

**Issue by jandeschuttere** [home-assistant/wheels#458]
Referring to https://github.com/home-assistant/core/issues/74067 (and related https://github.com/home-assistant/core/issues/74952(

After some initial research I believe the ADS package issue correlates with https://github.com/home-assistant/docker/pull/236 where the transition seems to be done to move to musllinux wheel.

I am willing to dive into this codebase and logic - when I find time - to identify what can be done to fix this, if someone can confirm this is a viable path. I am however not a python dev so it'll take me some time to catch up with wheels and how they interact with the codebase in terms of identification of requirements and how to identify which need different architecture targets.

**Comment by SaWey** [comment]
The problem is with the pyads library not being built for the different platforms.
It is using the binary adslib.so, but the wheels package is defined as being platform independant.
[pyads-3.2.2-py3-none-any.whl](https://wheels.home-assistant.io/musllinux/pyads-3.2.2-py3-none-any.whl)

Before the switch to musllinux, the packages were built per platform, but were named the same and seemed platform independant:
`Wheel-Version: 1.0`
`Generator: bdist_wheel (0.37.1)`
`Root-Is-Purelib: true`
`Tag: py3-none-any`

I can't find info on how/when the wheel is built by HA and how it is defined to only produce the *py3-none-any.whl file

**Comment by SaWey** [comment]
I found some time to search the problem, and I think I found the reason why this has been failing all along.
pyads is building the adslib dependency in a special way which goes unnoticed by setuptools.

The library would need a special switch to let setuptools build the wheel with a platform specific name.

> https://stackoverflow.com/a/64921892 (by CiaranWelsh):
> Adding below line to setup arguments in setup.py
> `has_ext_modules=lambda: True
> `
> This let me build pyads-3.3.9-cp310-cp310-linux_x86_64.whl instead of pyads-3.3.9-py3-none-any.whl

So probably nothing to do with the way HA is building the wheels.

I have made [a pull request](https://github.com/stlehmann/pyads/pull/363) on the library in the hope they will include it.
